data1 = float(input())
data2 = float(input())
data3 = float(input())
data4 = float(input())
data5 = float(input())
data6 = float(input())
data7 = float(input())
data8 = float(input())
data9 = float(input())
data10 = float(input())
data11 = float(input())
data12 = float(input())
data13 = float(input())
data14 = float(input())
data15 = float(input())
data16 = float(input())
data17 = float(input())
data18 = float(input())
data19 = float(input())
data20 = float(input())
data21 = float(input())
data22 = float(input())
data23 = float(input())
data24 = float(input())
datalist = [data1 , data2 , data3 , data4 , data5 , data6 , data7 , data8 , data9 , data10 , data11 , data12 , data13 , data14 , data15 , data16 , data17 , data18 , data19 , data20 , data21 , data22 , data23 , data24]

def foodgrade1():

foodgrade1()

#คิดว่าต้อง pop ข้อมูลที่ อยู่นอกเหนือจาก 50 - 70 ออกก่อน แล้วใช้ len() นับจำนวนที่เหลือ print(len(datapass))